### ISSUE TITLE
Lazy initialisation

### ISSUE THREAD

**Issue by mwoodbri** [esoreq/minder-downloader#4]
Prompt for API token should be suppressed until the token is actually required i.e. when downloading data. This would enable use of utility functions without a token. At the moment, importing the functions as follows causes the prompt to appear, which isn't compatible with using these functions in non-interactive environments e.g. unit tests.

```py
from minder_downloader.utils import localize_time, mine_transition
```

**Comment by esoreq** [comment]
Resolved to embed prompt within MinderDatasetDownload class

**Comment by mwoodbri** [comment]
I think there's still an issue with latest release? As soon as the package is imported it looks for the config file - which doesn't seem to exist yet.

```python
import minder_downloader as md
# __init__.py:
from .download import load 
# download.py:
from .info import _minder_datasets_info,_minder_organizations_info
# info.py:
os.environ['MINDER_TOKEN'] = load_yaml(INFO_PATH)['token']
```

Ideally we'd like to be able to set `RESEARCH_PORTAL_TOKEN_PATH` (to point to file containing token) and `MINDER_DOWNLOADER_HOME` (to point to a writable folder) and then import the package. At which point the config file would be created automatically in the correct location, if it doesn't already exist.

**Comment by esoreq** [comment]
Just to clarify the RESEARCH_PORTAL_TOKEN_PATH should contain the same yaml file
So what you want is for the downloader to search for the environment variable and if it exists use it to set the config parameters?
That include the writable output folder

From: Mark Woodbridge ***@***.***>
Date: Wednesday, 5 April 2023 at 11:39
To: esoreq/minder-downloader ***@***.***>
Cc: Soreq, Eyal ***@***.***>, State change ***@***.***>
Subject: Re: [esoreq/minder-downloader] Lazy initialisation (Issue #4)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



I think there's still an issue with latest release? As soon as the package is imported it looks for the config file - which doesn't seem to exist yet.

import minder_downloader as md

# __init__.py:

from .download import load

# download.py:

from .info import _minder_datasets_info,_minder_organizations_info

# info.py:

os.environ['MINDER_TOKEN'] = load_yaml(INFO_PATH)['token']

Ideally we'd like to be able to set RESEARCH_PORTAL_TOKEN_PATH (to point to file containing token) and MINDER_DOWNLOADER_HOME (to point to a writable folder) and then import the package. At which point the config file would be created automatically in the correct location, if it doesn't already exist.

**Comment by mwoodbri** [comment]
`RESEARCH_PORTAL_TOKEN_PATH` points to a file containing a token. It only contains the token and nothing else: it's a plain text file, not YAML. It is injected into the runtime container when created by Kubeflow.

`MINDER_DOWNLOADER_HOME` points to a folder on a writable filesystem and should be used by the library to store any files it creates e.g. dynamically created config files or temporary files.

Basic requirement is that after these two variables are set minder-downloader package can be used entirely non-interactively and without any further configuration. And that it writes files only to the specified directory i.e. not the Python packages folder (as present) or anywhere else - because almost all other locations are read-only by design.

**Comment by esoreq** [comment]
This now fixed in version 0.1.07


From: Mark Woodbridge ***@***.***>
Date: Monday, 17 April 2023 at 11:13
To: esoreq/minder-downloader ***@***.***>
Cc: Soreq, Eyal ***@***.***>, State change ***@***.***>
Subject: Re: [esoreq/minder-downloader] Lazy initialisation (Issue #4)
This email from ***@***.*** originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



RESEARCH_PORTAL_TOKEN_PATH points to a file containing a token. It only contains the token and nothing else: it's a plain text file, not YAML. It is injected into the runtime container when created by Kubeflow.

MINDER_DOWNLOADER_HOME points to a folder on a writable filesystem and should be used by the library to store any files it creates e.g. dynamically created config files or temporary files.

Basic requirement is that after these two variables are set minder-downloader package can be used entirely non-interactively and without any further configuration. And that it writes files only to the specified directory i.e. not the Python packages folder (as present) or anywhere else - because almost all other locations are read-only by design.
